### ISSUE TITLE
Conflict with mkdocs-markdownextradata-plugin

### ISSUE THREAD

**Issue by G3rtjan** [timvink/mkdocs-table-reader-plugin#20]
When using both the `mkdocs-markdownextradata-plugin` and this `mkdocs-table-reader-plugin`, there is a conflict when using the `{{ read_csv("table.csv") }}` (and other) placeholders from `mkdocs-table-reader-plugin` which are tried to be interpreted as `mkdocs-markdownextradata-plugin` placeholders.

When running `mkdocs serve` on docs containing `{{ read_csv("table.csv") }}`, then an error occurs:
`jinja2.exceptions.UndefinedError: 'read_csv' is undefined`.
This seems to be caused by the `mkdocs-table-reader-plugin` placeholders to be trying to be interpreted as `mkdocs-markdownextradata-plugin` placeholders, because both rely on the same `{{ placeholder }}` pattern within the markdown docs.

A temporary solution is to specify a different placeholder pattern for `mkdocs-markdownextradata-plugin` in the `mkdocs.yml`:
```
plugins:
    - search
    - markdownextradata:
        jinja_options:
            variable_start_string: "{{{"
            variable_end_string: "}}}"
```
