### ISSUE TITLE
URL Recognition from data source

### ISSUE THREAD

**Issue by iamstrained** [timvink/mkdocs-table-reader-plugin#48]
If you are attempting to feed CSV data to the data table conversion (such as outbound links for public sites/beyond your MKDocs local paths) they do not auto convert using this plugin to viable links.

Would be a nice enhancement to work on the link conversion when parsed as a final value-add or Option set to enable.

**Comment by timvink** [comment]
Hi @iamstrained,

Could you elaborate a bit? Do you have a small example with the current output and the output/syntax you have in mind?

**Comment by timvink** [comment]
You can use regular markdown markup.

Consider the following yaml file:

```yaml
- name: google
  link: https://www.google.com
- name: bing
  link: https://www.bing.com  
- name: another
  link: "[bing](https://www.bing.com)"
- name: and
  link: "<https://www.bing.com>"
``` 

That renders as:

![image](https://github.com/timvink/mkdocs-table-reader-plugin/assets/5570380/4a7690fd-b13c-4bce-b900-b91aa7ba57a8)

Also note that normal links in markdown also do not auto-convert to links.

What you are probably looking for is https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/ . Please re-open if I misinterpreted your message :)
